CREATE TABLE PRODUCTS (
	[Id]		BIGINT IDENTITY (1, 1)	NOT NULL,
	[Name]		VARCHAR (150)			NULL,
	CONSTRAINT [PK_PRODUCTS] PRIMARY KEY CLUSTERED ([Id] ASC)
);

INSERT INTO PRODUCTS
VALUES
	(1, 'Product1'),
	(2, 'Product2'),
	(3, 'Product3');

CREATE TABLE CATEGORIES (
	[Id]	BIGINT IDENTITY (1, 1)	NOT NULL,
	[Name]	VARCHAR (150)			NULL,
	CONSTRAINT [PK_CATEGORIES] PRIMARY KEY CLUSTERED ([Id] ASC)
);

INSERT INTO CATEGORIES
VALUES
	(1, 'Categories1'),
	(2, 'Categories2'),
	(3, 'Categories3');

CREATE TABLE PRODUCT_CATEGORIES (
	[Id]				BIGINT IDENTITY (1, 1)	NOT NULL,
	[ProductId]			BIGINT FOREIGN KEY REFERENCES Products(Id),
	[CategoryId]		BIGINT FOREIGN KEY REFERENCES Categories(Id),
	CONSTRAINT [PK_PRODUCT_CATEGORIES] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_PRODUCT_CATEGORIES_PRODUCTS] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[PRODUCTS] ([Id]),
	CONSTRAINT [FK_PRODUCT_CATEGORIES_CATEGORIES] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[CATEGORIES] ([Id]),
);

INSERT INTO PRODUCT_CATEGORIES
VALUES
	(1, 1),
	(1, 3),
	(2, 2);

SELECT p.Name, c.Name
FROM PRODUCTS						P	WITH (NOLOCK)
	LEFT JOIN PRODUCT_CATEGORIES	PC	WITH (NOLOCK)
		ON P.Id = PC.ProductId
	LEFT JOIN CATEGORIES			C	WITH (NOLOCK)
		ON PC.CategoryId = C.Id;